"""This module contains the code that describes a Bat object and its behaviours"""

import random

import numpy as np
from agents.class_sounds import DirectSound
from supporting_files.bats_response_to_sound import (
    decide_next_direction_based_on_consistency,
    decide_next_direction_based_on_loudest_sound,
)
from supporting_files.snr_implementation import (
    given_sound_objects_return_detected_sounds,
)
from supporting_files.supporting_functions_for_consistency import (
    given_parameters_df_return_grid_matrix_zeros,
)
from supporting_files.utilities import (
    call_directionality_factor,
    make_dir,
    read_temporal_masking_fn,
    str2bool,
)
from supporting_files.vectors import Vector


class Bat:
    _id_counter = 0

    def __init__(self, parameters_df, output_dir, store_hearing):
        self.id = Bat._id_counter
        Bat._id_counter += 1

        self.parameters_df = parameters_df.copy()
        self.position = Vector(
            random.uniform(1, self.parameters_df["ARENA_WIDTH"][0] - 1),
            random.uniform(1, self.parameters_df["ARENA_HEIGHT"][0] - 1),
        )
        angular_resolution = np.radians(parameters_df["BAT_ANGULAR_RESOLUTION"][0])
        self.direction = Vector().random_direction()  # randomize start direction
        self.allocentric_axis_y = Vector(
            -np.tan(angular_resolution), 1
        )  # self.direction
        time_step_size = self.parameters_df["TIME_STEP"][0]
        # find the number of decimal places to set rounding equal to time step size
        self.rounding_based_on_time_step = len(str(time_step_size).split(".")[1])

        self.call_rate = self.parameters_df["CALL_RATE"][0]
        self.time_since_last_call = np.round(
            random.uniform(0, 1 / self.call_rate),
            self.rounding_based_on_time_step,
        )
        self.store_hearing = store_hearing
        # only stores DirectSound objects that was generated by it
        self.emitted_sounds = []
        self.emit_times = [-np.inf]

        # stores all received sounds
        # EchoSound of its own calls plus DirectSound + EchoSound of other bats
        self.received_sounds = []
        # stores all the position information
        self.position_history = []

        # clean up activates after every some steps to clear memory from RAM and store it on drive
        self.time_since_last_cleanup = self.time_since_last_call

        self.output_dir = output_dir
        self.speed = self.parameters_df["BAT_FAST_SPEED"][0]  # initial speed
        self.radius = self.parameters_df["BAT_RADIUS"][0]  # bat radius

        self.detections_for_directon_change = []  # initiate detection list
        self.time_since_directon_change = -np.inf  # time counter, direction change
        self.next_direction = self.direction  #

        self.implement_snr = str2bool(self.parameters_df["IMPLEMENT_SNR"][0])

        self.hearing_angle_threshold = np.radians(
            self.parameters_df["HEARING_ANGLE_THRESHOLD"][0]
        )
        # self.temporal_masking_file_dir
        self.min_sound_detection_fraction = self.parameters_df[
            "MINIMUM_SOUND_DETECTION_FRACTION"
        ][0]
        self.include_direct_sounds_in_response = str2bool(
            self.parameters_df["INCLUDE_DIRECT_SOUNDS_IN_RESPONSE"][0]
        )
        self.temporal_masking_file = read_temporal_masking_fn(
            "./dynamic_model/supporting_files/temporal_masking_fn.csv"
        )
        self.memory_window_to_store_grids = []

        self.responding_to_direction = (np.nan, np.nan)
        self.response_type = None
        self.cell_index_to_respond_to = [np.nan, np.nan]

        # self.reaction_state = None
        # self.reaction_time = -np.inf
        self.ipi_matrix = given_parameters_df_return_grid_matrix_zeros(
            self.parameters_df
        )[0]
        self.memory_window_sum_matrix = self.ipi_matrix.copy()
        # print(self.ipi_matrix)

        self.ipi_matrix_timeseries = []
        self.memory_window_to_store_grids_timeseries = []

        self.any_consistent_sound = "no"
        self.kill_movement = str2bool(self.parameters_df["KILL_MOVEMENT"][0])
        self.is_bat_reflective_to_sound = str2bool("yes")

        self.special_boundary_rules = self.parameters_df["SPECIAL_BOUNDARY_RULES"][0]

    def update(self, current_time, sound_objects):
        """Function to update bats with time.
        This function handles movement update of bat each time step.
        Also takes care of sound emission, detection of active sounds by the bats.
        Bat detections over time is also cleared and stored locally.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (EchoSound): direct and echo sounds that are currently active.
        """

        if not self.kill_movement:
            self.update_movement()
            self.position_history.append(
                (current_time, (self.position.x, self.position.y))
            )
        self.emit_sounds(current_time, sound_objects)
        if not self.kill_movement:
            self.update_directon(current_time, sound_objects)
            self.cleanup_sounds(current_time)
            self.detect_sounds(current_time, sound_objects)

        if self.id == 0 and self.time_since_directon_change == 0:
            print(current_time)

    def update_movement(self):
        """Update poisition of Bat when called.
        Every timestep the position of the bat needs to be
        updated based on velcoity and direction.
        """
        self.position += (
            self.direction * self.speed * self.parameters_df["TIME_STEP"][0]
        )

        # Boundary checks with bounce

        if (
            self.position.x <= 0
            or self.position.x >= self.parameters_df["ARENA_WIDTH"][0]
        ):
            self.direction.x *= -1
            self.next_direction = self.direction
        if (
            self.position.y <= 0
            or self.position.y >= self.parameters_df["ARENA_HEIGHT"][0]
        ):
            self.direction.y *= -1
            self.next_direction = self.direction

    def emit_sounds(self, current_time, sound_objects):
        """Trigger sound emission by Bat.
        Whenever the function is called, it checks if sufficient time
        has passed and a DirectSoundObject is created.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): List containing all active sounds in the simulation
        """
        self.time_since_last_call += self.parameters_df["TIME_STEP"][0]
        call_interval = 1.0 / self.call_rate

        if self.time_since_last_call >= call_interval:
            sound = DirectSound(
                parameters_df=self.parameters_df,
                origin=self.position,
                creation_time=current_time,
                emitter_id=self.id,
                direction_vector=self.direction,
            )
            self.emitted_sounds.append(sound)
            self.emit_times.append(current_time)
            sound_objects.append(sound)

            self.next_direction = self.direction
            self.time_since_directon_change = -self.parameters_df["CALL_DURATION"][0]
            self.time_since_last_call = np.random.uniform(
                -self.parameters_df["NOISE_IN_CALL_RATE"][0],
                self.parameters_df["NOISE_IN_CALL_RATE"][0],
            )
            self.detections_for_directon_change = []
            self.time_since_last_cleanup = 0

    def convert_sound_to_dictionary(self, sound, current_time, received_spl):
        """converts a given sound to dictionary
        inorder to save only necessary information

        Args:
            sound (EchoSound): sound to convert
            current_time (float): simulation time
            received_spl (float): spl at the focal bat after sound directionaility
                        and spreading

        Returns:
            dictionary: dictionary version of the sound object
        """
        incident_direction = sound.origin - self.position
        sound_type = "direct" if isinstance(sound, DirectSound) else "echo"

        dictionary = {
            "time": current_time,
            "origin": (sound.origin.x, sound.origin.y),
            "distance_from_bat": sound.origin.distance_to(self.position),
            "received_spl": received_spl,
            "emitter_id": sound.emitter_id,
            "type": sound_type,
            "reflection_count": getattr(sound, "reflection_count", 0),
            "reflected_from": sound.reflected_from,
            "sound_object_id": sound.id,
            "sound_direction": (
                sound.direction_vector.x,
                sound.direction_vector.y,
            ),
            "incident_direction": (
                incident_direction.x,
                incident_direction.y,
            ),
            "bat_direction": (self.direction.x, self.direction.y),
            "bat_position": (self.position.x, self.position.y),
            "bat_last_call_time": self.emit_times[-1],
        }
        return dictionary

    def given_sound_objects_return_sounds_at_bat_position(
        self, current_time, sound_objects
    ):
        """given sounds generate list of sounds that a bat can hear

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): List containing all active sounds in the simulation
            detect_self_call (Bool): If true, add self call to detected, else, skip self call.

        Returns:
            list: sound detections given time.
        """
        array_of_sound_detections = []
        # if bat is calling it shouldnt hear anything
        is_bat_calling = (
            current_time < self.emit_times[-1] + self.parameters_df["CALL_DURATION"][0]
        )
        if is_bat_calling:
            return array_of_sound_detections
        for sound in sound_objects:
            sound.update(current_time)

            is_sound_active = sound.active
            is_sound_self_call = sound.emitter_id == self.id and isinstance(
                sound, DirectSound
            )
            is_sound_reflected_from_self = sound.reflected_from == f"bat_{self.id}"

            if (
                not is_sound_active
                or is_sound_self_call
                or is_sound_reflected_from_self
            ):
                continue

            # sound can only be detected if bat is inside the sound wave
            if sound.contains_point(self.position):
                received_spl = sound.spl_at_receiver(self.position)

                angle_between_sound_and_bat = sound.direction_vector.angle_between(
                    self.position
                )
                hearing_directionality = call_directionality_factor(
                    A=self.parameters_df["HEARING_DIRECTIONALITY"][0],
                    theta=angle_between_sound_and_bat,
                )

                received_spl += hearing_directionality
                is_sound_audible = (
                    received_spl > self.parameters_df["MIN_DETECTABLE_SPL"][0]
                )

                if not is_sound_audible:
                    continue
                array_of_sound_detections.append(
                    self.convert_sound_to_dictionary(sound, current_time, received_spl)
                )
        return array_of_sound_detections

    def detect_sounds(self, current_time, sound_objects):
        """Detects sound that are audible to the Bat
        Checks if a bat can hear a sound based on dbSpl of sound
        and position of bat.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): _description_
        """
        self.received_sounds.extend(
            self.given_sound_objects_return_sounds_at_bat_position(
                current_time, sound_objects
            )
        )
        self.ipi_matrix_timeseries.append(self.ipi_matrix)
        self.memory_window_to_store_grids_timeseries.append(
            self.memory_window_to_store_grids
        )

    def cleanup_sounds(self, current_time):
        """Stores the detections into a .npy file.
        After a fixed amount of time the detection list is stored
        into local memory and this is cleared from RAM.

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
        """
        # Keep only recent detections

        if self.time_since_last_cleanup == 0:
            if self.store_hearing:
                dir_to_store = self.output_dir + "/" + str(self.id)
                make_dir(dir_to_store)
                current_time_str = f"{current_time:.4f}".zfill(9)
                np.save(
                    dir_to_store
                    + f"/bat_{self.id}_received_sounds_snapshot_at_time_{current_time_str}.npy",
                    self.received_sounds,
                )
                np.save(
                    dir_to_store
                    + f"/bat_{self.id}_emitted_sounds_snapshot_at_time_{current_time_str}.npy",
                    self.emitted_sounds,
                )
                np.save(
                    dir_to_store
                    + f"/bat_{self.id}_ipi_matrix_snapshot_at_time_{current_time_str}.npy",
                    self.ipi_matrix_timeseries,
                )
                np.save(
                    dir_to_store
                    + f"/bat_{self.id}_sum_matrix_snapshot_at_time_{current_time_str}.npy",
                    self.memory_window_to_store_grids_timeseries,
                )
            self.time_since_last_cleanup = -np.inf
            self.emitted_sounds = []
            self.received_sounds = []
            self.ipi_matrix_timeseries = []
            self.memory_window_to_store_grids_timeseries = []

    def get_detections_at_time(self, current_time):
        """

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.

        Returns:
            list: sounds that are detected by a bat before a certain time.
        """
        return [d for d in self.received_sounds if d["time"] <= current_time]

    # inelligent movement
    def generate_random_direction(self):
        """assign a random direction to the bat"""
        direction = self.direction
        if random.random() < self.parameters_df["PROPENSITY_TO_CHANGE_DIRECTION"][0]:
            direction = Vector().random_direction()
        return direction

    def generate_direction_vector_given_sound(self, sound):
        """generate direction vector of any sound

        Args:
            sound (EchoSound): sound to convert to vector

        Returns:
            Vector: Vector form of the input sound
        """
        spl_of_sound = sound["received_spl"]

        normalized_sound_vector = (
            Vector(x=sound["origin"][0], y=sound["origin"][1]) - self.position
        ).normalize()

        vector_w_spl_magnitude = normalized_sound_vector * spl_of_sound
        return vector_w_spl_magnitude

    def decide_next_direction(self, detected_sound_objects):
        """decide next direction of bat based on sound"""
        behaviour_rule_to_use = self.parameters_df["BEHAVIOUR_RULE"][0]

        if behaviour_rule_to_use == "consistency":
            next_direction, response_type = decide_next_direction_based_on_consistency(
                self, detected_sound_objects
            )
        elif behaviour_rule_to_use == "loudest_sound":
            next_direction, response_type = (
                decide_next_direction_based_on_loudest_sound(
                    self, detected_sound_objects
                )
            )
        else:
            # print(behaviour_rule_to_use)
            # print(behaviour_rule_to_use == "consistency")
            raise ValueError("unsupported behaviour rule")
        return next_direction.normalize(), response_type

    def update_directon(self, current_time, sound_objects):
        """rotate bat according to fix angular speed

        Args:
            current_time (float): Time, in seconds, for which the simualtion has been running.
            sound_objects (list): list containing detected sounds
        """
        self.time_since_directon_change += self.parameters_df["TIME_STEP"][0]
        # self.reaction_time += self.parameters_df["TIME_STEP"][0]
        direction_change_time_interval = self.parameters_df[
            "TIME_DELAY_FOR_DIRECTION_CHANGE"
        ][0]
        self.detections_for_directon_change.extend(
            self.given_sound_objects_return_sounds_at_bat_position(
                current_time, sound_objects
            )
        )

        if (
            self.time_since_directon_change >= direction_change_time_interval
            and len(self.detections_for_directon_change) != 0
        ):
            # print(len(self.detections_for_directon_change))
            if self.implement_snr:
                heard_sounds = given_sound_objects_return_detected_sounds(
                    self.detections_for_directon_change,
                    direction_change_time_interval,
                    self.hearing_angle_threshold,
                    self.temporal_masking_file,
                    self.min_sound_detection_fraction,
                    self.id,
                    self.include_direct_sounds_in_response,
                    self.parameters_df["CALL_DURATION"][0],
                    self.parameters_df["TIME_STEP"][0],
                    self.rounding_based_on_time_step,
                )
            else:
                heard_sounds = self.detections_for_directon_change

            if self.any_consistent_sound == "no":
                self.speed = self.parameters_df["BAT_FAST_SPEED"][0]
                self.call_rate = self.parameters_df["CALL_RATE_FAST"][0]
            else:
                self.speed = self.parameters_df["BAT_SPEED"][0]
                self.call_rate = self.parameters_df["CALL_RATE"][0]

            self.next_direction, self.response_type = self.decide_next_direction(
                heard_sounds
            )
            self.detections_for_directon_change = []
            self.time_since_directon_change = -np.inf
            # self.reaction_time = 0
            # self.reaction_state = "responding"
            if self.next_direction != self.direction.normalize():
                self.responding_to_direction = (
                    self.next_direction.x,
                    self.next_direction.y,
                )
            else:
                self.responding_to_direction = (np.nan, np.nan)

            if self.response_type == "attraction":
                self.speed = self.parameters_df["BAT_FAST_SPEED"][0]
        elif (
            self.time_since_directon_change >= direction_change_time_interval
            and len(self.detections_for_directon_change) != 0
        ):
            self.ipi_matrix = given_parameters_df_return_grid_matrix_zeros(
                self.parameters_df
            )[0]
            self.memory_window_sum_matrix = self.ipi_matrix.copy()
            # print("oh this part running rrn")
        # if self.reaction_time >= self.parameters_df["REACTION_TIME"][0]:
        #     print("aaa")
        #     self.reaction_state = None
        #     self.reaction_time = -np.inf
        rotation_speed = self.parameters_df["BAT_ROTATION_SPEED"][0]
        rotation_speed_scaled_by_time_step = (
            rotation_speed * self.parameters_df["TIME_STEP"][0]
        )
        self.rotate_towards_given_degree(
            self.next_direction, rotation_speed_scaled_by_time_step
        )

    def rotate_towards_given_degree(self, new_direction, rotation_rate):
        """slowly rotate towards the new_direction from current_direction

        Args:
            new_direction (Vector): direction that the bat wants to end up in
            rotation_rate (Vector)): radians rotated per time step
        """

        current_direction = self.direction
        if current_direction != new_direction:
            angle_between_current_and_new = current_direction.angle_between(
                new_direction
            )

            if angle_between_current_and_new > rotation_rate:
                rotation_angle = 1 * rotation_rate
            elif angle_between_current_and_new < -rotation_rate:
                rotation_angle = -1 * rotation_rate
            else:
                rotation_angle = angle_between_current_and_new

            rotated_vector = current_direction.rotate(rotation_angle)
            # print(
            #     f"next dir {self.next_direction}",
            #     f"dir {self.direction}",
            #     f"angle {self.direction.angle_between(self.next_direction)}",
            #     f"rotation angle {self.direction}",
            # )
            self.direction = rotated_vector.normalize()

    # def aditya(self)

    # def update_call_rate(self):
    #     change_call_rate = str2bool(self.parameters_df["ENABLE_ADAPTIVE_CALL_RATE"][0])
    #     call_rate_method = self.parameters_df["ADAPTIVE_CALL_RATE_METHOD"][0]
    #     if change_call_rate:
    #         if call_rate_method == "aditya":
    #             self.aditya()
    #         elif call_rate_method == "thejasvi":
    #             self.thejasvi()
    #         else:
    #             raise ValueError("not supported adaptive call rate method")
    #     else:
    #         self.

    def __repr__(self):
        return f"Bat(id={self.id}, position={self.position})"
